namespace: logging-system

nameOverride: logging

lokiStack:
  name: logging
  namespace: openshift-logging
  size: 1x.demo
  storage:
    secretName: logging-loki-s3
    effectiveDate: "2024-01-01"
  tenant: application
  minio:
    endpoint: http://minio.tracing-system.svc.cluster.local:9000
    bucket: loki
    accessKeyId: tempo
    accessKeySecret: tempo12345

alloy:
  image:
    repository: grafana/alloy
    tag: "v1.8.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  bookinfo:
    namespace: bookinfo
    apps:
      - productpage
      - reviews
      - details
      - ratings
