nameOverride: logging

clusterLogForwarder:
  name: instance
  serviceAccountName: collector
  outputName: lokistack-out
  pipelineName: application-logs
  inputRefs:
    - application

lokiStack:
  name: logging
  namespace: openshift-logging
  size: 1x.demo
  storage:
    secretName: logging-loki-s3
    effectiveDate: "2024-01-01"
  tenant: application
  minio:
    endpoint: http://minio.tracing-system.svc.cluster.local:9000
    bucket: loki
    accessKeyId: tempo
    accessKeySecret: tempo12345
