apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookinfo-details-monitor
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      app: details
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookinfo-ratings-monitor
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      app: ratings
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookinfo-reviews-monitor
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      app: reviews
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookinfo-productpage-monitor
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      app: productpage
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
