apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    {{- if .Values.datasources.prometheus.enabled }}
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.datasources.prometheus.url | quote }}
        isDefault: true
        jsonData:
          httpMethod: POST
          tlsSkipVerify: true
          timeInterval: 30s
          httpHeaderName1: Authorization
        secureJsonData:
          httpHeaderValue1: Bearer $__file{/var/run/secrets/kubernetes.io/serviceaccount/token}
    {{- end }}
    {{- if .Values.datasources.tempo.enabled }}
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: {{ include "grafana.tempo.url" . | quote }}
        jsonData:
          tlsSkipVerify: true
          httpHeaderName1: Authorization
          httpMethod: GET
          tracesToMetrics:
            datasourceUid: prometheus
          tracesToLogs:
            datasourceUid: loki
            filterByTraceID: true
            mapTagNamesEnabled: true
            tags:
              - key: namespace
                value: bookinfo
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
        secureJsonData:
          httpHeaderValue1: Bearer $__file{/var/run/secrets/kubernetes.io/serviceaccount/token}
    {{- end }}
    {{- if .Values.datasources.loki.enabled }}
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: {{ include "grafana.loki.url" . | quote }}
        jsonData:
          maxLines: 1000
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id":"(\\w+)"'
              url: "$${__value.raw}"
              datasourceUid: tempo
            - name: TraceID
              matcherRegex: 'trace_id=(\\w+)'
              url: "$${__value.raw}"
              datasourceUid: tempo
    {{- end }}
