apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    {{- include "grafana.instanceLabels" . | nindent 4 }}
spec:
  version: {{ .Values.image.tag | quote }}
  config:
    log:
      mode: console
    security:
      admin_user: {{ .Values.admin.user | quote }}
      admin_password: {{ .Values.admin.password | quote }}
  {{- if .Values.route.enabled }}
  {{- if .Values.route.host }}
  route:
    spec:
      host: {{ .Values.route.host | quote }}
  {{- else }}
  route:
    spec: {}
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
  deployment:
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        spec:
          serviceAccountName: {{ include "grafana.fullname" . }}
          automountServiceAccountToken: true
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: grafana
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
