apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.user | quote }}
  admin-password: {{ .Values.admin.password | quote }}
