apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
