app:
  name: default
  namespace: bookinfo

# Required on namespaces with ResourceQuota that enforce requests.*
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 256Mi
