#----------------------------------------------------------------------------------
# Installs the Red Hat OpenShift Logging Operator (required for ClusterLogForwarder)
# Required before 13-logging.yaml (ClusterLogForwarder)
#----------------------------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-logging-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-operators-redhat
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/nicknas/service-mesh-3-demo.git
    targetRevision: main
    path: service-mesh-deployments/v3-gw-api-otel/helm-charts/cluster-logging-operator
