{{- if and .Values.dynatrace.enabled .Values.dynatrace.secret.create .Values.dynatrace.secret.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dynatrace.secret.name }}
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  apiToken: {{ .Values.dynatrace.secret.apiToken | quote }}
{{- end }}
