subscription:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.21.3

argocd:
  name: openshift-gitops
  namespace: openshift-gitops
  applicationController:
    clusterAdmin: true
  rbac:
    enabled: true
    defaultPolicy: role:readonly
    scopes: '[groups]'
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, system:authenticated, role:readonly
  resourceCustomizations: |
    /PersistentVolumeClaim:
      health.lua: |
        hs = {}
        if obj.status ~= nil and obj.status.phase == "Bound" then
          hs.status = "Healthy"
          hs.message = "Bound"
          return hs
        end
        if obj.status ~= nil and obj.status.phase == "Pending" then
          hs.status = "Healthy"
          hs.message = "Pending is acceptable for WaitForFirstConsumer"
          return hs
        end
        hs.status = "Progressing"
        hs.message = "Waiting for PVC"
        return hs
