# Secret con las credenciales de acceso a minio
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: tracing-system
type: Opaque
stringData:
  endpoint: "http://papandujo.tia.com:9000"
  bucket: "tempo"
  access_key_id: "adminuser"
  access_key_secret: "adminuser"
  insecure: "true"  # HTTP (sin TLS)
