# Secret con las credenciales de acceso a minio
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: tracing-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  endpoint: {{ .Values.minio.endpoint | quote }}
  bucket: {{ .Values.minio.bucket | quote }}
  access_key_id: {{ .Values.minio.accessKeyId | quote }}
  access_key_secret: {{ .Values.minio.accessKeySecret | quote }}
  insecure: {{ .Values.minio.insecure | quote }}
