# Secret con las credenciales de acceso a minio
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: tracing-system
type: Opaque
stringData:
  endpoint: "https://<minio-server>"
  bucket: "tempo"
  access_key_id: "********"
  access_key_secret: "********"
  insecure: "true"  # HTTP (sin TLS)
