minio:
  endpoint: "http://minio.tracing-system.svc.cluster.local:9000"
  bucket: tempo
  accessKeyId: tempo
  accessKeySecret: tempo12345
  insecure: "true"

# UIPlugin DistributedTracing requires Cluster Observability Operator CRD.
uiPlugin:
  enabled: false
