apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: {{ .Values.clusterLogForwarder.name }}
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    {{- include "logging.labels" . | nindent 4 }}
spec:
  serviceAccount:
    name: {{ .Values.clusterLogForwarder.serviceAccountName }}
  outputs:
    - name: {{ .Values.clusterLogForwarder.outputName }}
      type: lokiStack
      lokiStack:
        target:
          name: {{ .Values.lokiStack.name }}
          namespace: {{ .Values.lokiStack.namespace }}
        authentication:
          token:
            from: serviceAccount
      tls:
        ca:
          configMapName: {{ include "logging.lokiStack.gatewayCaConfigMap" . }}
          key: service-ca.crt
  pipelines:
    - name: {{ .Values.clusterLogForwarder.pipelineName }}
      inputRefs:
        {{- toYaml .Values.clusterLogForwarder.inputRefs | nindent 8 }}
      outputRefs:
        - {{ .Values.clusterLogForwarder.outputName }}
