apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lokiStack.storage.secretName }}
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "logging.labels" . | nindent 4 }}
type: Opaque
stringData:
  bucketnames: {{ .Values.lokiStack.minio.bucket | quote }}
  endpoint: {{ .Values.lokiStack.minio.endpoint | quote }}
  access_key_id: {{ .Values.lokiStack.minio.accessKeyId | quote }}
  access_key_secret: {{ .Values.lokiStack.minio.accessKeySecret | quote }}
  forcepathstyle: "true"
