apiVersion: v1
kind: Service
metadata:
  name: {{ include "logging.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "logging.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: loki
    app.kubernetes.io/name: {{ include "logging.name" . }}
  ports:
    - name: http
      port: {{ .Values.loki.service.port }}
      targetPort: http
