apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logging.fullname" . }}-loki
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "logging.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: loki
      app.kubernetes.io/name: {{ include "logging.name" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "logging.labels" . | nindent 8 }}
        app.kubernetes.io/component: loki
    spec:
      serviceAccountName: {{ include "logging.fullname" . }}-loki
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - name: http
              containerPort: {{ .Values.loki.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: {{ include "logging.fullname" . }}-loki-config
        - name: data
          {{- if .Values.loki.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "logging.fullname" . }}-loki
          {{- else }}
          emptyDir: {}
          {{- end }}
