apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "logging.labels" . | nindent 4 }}
