{{- if and .Values.enabled .Values.dynaKube.apiUrl }}
apiVersion: {{ .Values.dynaKube.apiVersion | default "dynatrace.com/v1beta4" }}
kind: DynaKube
metadata:
  name: {{ .Values.dynaKube.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- if eq .Values.dynaKube.mode "managed" }}
    argocd.argoproj.io/sync-options: Delete=false
    {{- if .Values.dynaKube.annotations.automaticKubernetesApiMonitoring }}
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    {{- end }}
    feature.dynatrace.com/oneagent-seccomp-profile: {{ .Values.dynaKube.annotations.oneagentSeccompProfile | default "" | quote }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "dynatrace.name" . }}
spec:
  apiUrl: {{ .Values.dynaKube.apiUrl | quote }}
  {{- if .Values.dynaKube.networkZone }}
  networkZone: {{ .Values.dynaKube.networkZone | quote }}
  {{- end }}
  {{- if .Values.dynaKube.dynatraceApiRequestThreshold }}
  dynatraceApiRequestThreshold: {{ .Values.dynaKube.dynatraceApiRequestThreshold }}
  {{- end }}
  {{- if eq .Values.dynaKube.mode "managed" }}
  tokens: {{ .Values.secret.name }}
  {{- if .Values.trustedCA.name }}
  trustedCAs: {{ .Values.trustedCA.name }}
  {{- end }}
  metadataEnrichment:
    enabled: {{ .Values.dynaKube.metadataEnrichment.enabled }}
    namespaceSelector: {}
  {{- if .Values.dynaKube.activeGate.enabled }}
  activeGate:
    capabilities:
      {{- toYaml .Values.dynaKube.activeGate.capabilities | nindent 6 }}
    {{- if .Values.dynaKube.activeGate.image }}
    image: {{ .Values.dynaKube.activeGate.image | quote }}
    {{- end }}
    {{- with .Values.dynaKube.activeGate.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    replicas: {{ .Values.dynaKube.activeGate.replicas }}
    resources:
      {{- toYaml .Values.dynaKube.activeGate.resources | nindent 6 }}
    {{- with .Values.dynaKube.activeGate.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.dynaKube.oneAgent.classicFullStack.enabled }}
  oneAgent:
    classicFullStack:
      autoUpdate: {{ .Values.dynaKube.oneAgent.classicFullStack.autoUpdate }}
      {{- with .Values.dynaKube.oneAgent.classicFullStack.env }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dynaKube.oneAgent.classicFullStack.image }}
      image: {{ .Values.dynaKube.oneAgent.classicFullStack.image | quote }}
      {{- end }}
      {{- with .Values.dynaKube.oneAgent.classicFullStack.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      oneAgentResources:
        {{- toYaml .Values.dynaKube.oneAgent.classicFullStack.resources | nindent 8 }}
      {{- with .Values.dynaKube.oneAgent.classicFullStack.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
  templates:
    extensionExecutionController:
      imageRef: {}
      resources: {}
    kspmNodeConfigurationCollector:
      imageRef: {}
      nodeAffinity: {}
      resources: {}
    otelCollector:
      imageRef: {}
      resources: {}
  {{- else if eq .Values.dynaKube.mode "saas-ingest" }}
  {{- if .Values.dynaKube.telemetryIngest.enabled }}
  telemetryIngest:
    {{- if .Values.dynaKube.telemetryIngest.serviceName }}
    serviceName: {{ .Values.dynaKube.telemetryIngest.serviceName | quote }}
    {{- end }}
    protocols:
      {{- toYaml .Values.dynaKube.telemetryIngest.protocols | nindent 6 }}
  templates:
    otelCollector:
      imageRef:
        repository: {{ .Values.dynaKube.otelCollector.image.repository | quote }}
        tag: {{ .Values.dynaKube.otelCollector.image.tag | quote }}
  {{- end }}
  {{- end }}
{{- end }}
