{{- if and .Values.enabled .Values.secret.create .Values.secret.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: {{ include "dynatrace.name" . }}
type: Opaque
stringData:
  apiToken: {{ .Values.secret.apiToken | quote }}
  {{- if .Values.secret.dataIngestToken }}
  dataIngestToken: {{ .Values.secret.dataIngestToken | quote }}
  {{- end }}
{{- end }}
