{{- if and .Values.enabled .Values.trustedCA.create .Values.trustedCA.certs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.trustedCA.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: {{ include "dynatrace.name" . }}
data:
  certs: |
    {{- .Values.trustedCA.certs | nindent 4 }}
{{- end }}
