apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  endpoint: {{ include "minio.endpoint" . | quote }}
  bucket: {{ .Values.bucket | quote }}
  access_key_id: {{ .Values.auth.rootUser | quote }}
  access_key_secret: {{ .Values.auth.rootPassword | quote }}
  insecure: "true"
